; written by tds+ ui — overlaid on tds_abilities.ini
Toggle Reverse = off
Reposition = off
Call to Arms = chain 10
Support Caravan = off
Missile = off
Drop the Beat = off
Heatwave = off
Ice Turret = off
SWAT Van = off
Frost Grenade = off
FPS = off
War Cry = off
Hologram Tower = off
Thorns = off
Equip Bombs = off
Bounty = off
Ubercharge = off
Air-Drop = off
Airstrike = off
Raise the Dead = off
Sweeper = off
Patrol = off
Bee Swarm Grenade = off
Neuralyzed = off
fire aspect = off
